### ISSUE TITLE
How to upload the PWA File to Samsung store

### ISSUE THREAD

**Issue by rajandimri** [pwa-builder/pwabuilder-samsung#10]
Hello Team,
I want to upload the apk to the Samsung store and it asks for Binary. What are the binaries, how to upload it to the Samsung store?
1. https://prnt.sc/tr18ku
2. https://prnt.sc/tr18sd
is it the apk, that I need to upload? If yes, then I'm getting this error - https://prnt.sc/tr19sj

Please let me know further. 

Thank You :)

**Comment by rajandimri** [comment]
@jgw96 , @winstonchen could you please check this out?

**Comment by winstonchen** [comment]
@rajandimri let me check and I will get back to you. I think the binary is the apk that is generated.

**Comment by rajandimri** [comment]
@winstonchen I uploaded the generated apk from PWABuilder and got the error - https://prnt.sc/tr19sj

**Comment by rajandimri** [comment]
Hi, @winstonchen , just want to know if you got the time to gone through the issue :) 

Thank you

**Comment by winstonchen** [comment]
@rajandimri I am currently trying to find someone that can answer this. I am not the maintainer for the Samsung store. I will keep you posted.

**Comment by rajandimri** [comment]
Just wondering if anyone finds the solution?

**Comment by rajandimri** [comment]
Hello Team, You may be busy in other projects as well but please let me know if there any progress? @JudahGabriel & @winstonchen @jgw96

**Comment by JudahGabriel** [comment]
@rajandimri we'll get back to you about this. It appears the Samsung store changed significantly since we added this provider.

**Comment by rajandimri** [comment]
@JudahGabriel thank you, looking forward to publishing my app on Samsung store if this got a fix.

**Comment by JudahGabriel** [comment]
@rajandimri Can you open this issue over at the main PWABuilder repo? https://github.com/pwa-builder/pwabuilder/issues

**Comment by rajandimri** [comment]
> @rajandimri Can you open this issue over at the main PWABuilder repo? https://github.com/pwa-builder/pwabuilder/issues 

Done 👍
